application: jugglebee44
version: 1
runtime: python27
api_version: 1
threadsafe: no 

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: /static/images/favicon.ico
  upload: /static/favicon\.ico

- url: .*
  script: main.py
  secure: optional
